default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: courte_justice_development

test:
  <<: *default
  database: courte_justice_test

production:
  <<: *default
  database: courte_justice_production
  username: courte_justice
  password: <%= ENV["COURTE_JUSTICE_DATABASE_PASSWORD"] %>
